### ISSUE TITLE
Code fails when start_time  includes an hour figure

### ISSUE THREAD

**Issue by PeterKMcN** [jima80525/mp3splitter#3]
The line

            m,s = start_time.split(":")

causes and error when start_time includes an hour figure e.g. "01:07:38.222" because the split is trying to put 3 elements into 2 variables 

I suggest trap the error and split into h,m,s:

        try:
            m,s = start_time.split(":")
            m = int(m)
            h = 0
            while m > 59:
                h += 1
                m -= 60
            if h != 0:
                start_time = "{0:02}:{1:02}:{2}".format(h,m,s)
        except:
            h,m,s = start_time.split(":")

This worked for me but there may be a better solution as I don't write python and am unfamiliar with the program.

Hope this helps
Peter

**Comment by jima80525** [comment]
Peter!  THANK YOU for the feedback (both this bug and the other one!) This code was such a quick hack that I'm shocked anyone ever finds, much less uses it!  And now you're at least the second. :)

I would *swear* I already fixed this issue (as I ran into it the last time I used the tool), but it's not in git and it's not on my harddrive, so I must be dreaming.  I'll give this a look, but it might not happen until this weekend. 

Super fun to see people interested!

**Comment by jima80525** [comment]
OK. Now I'm confused.  I think you might be on an older version of the code?  The change you suggest above was put in on Nov 7th (SHA:572871a18fce126f0a4354e5f7d671c2f5081bf8)  It's pretty much identical to what you have above.  

Very strange.  I'm going to close this one - but please let me know if I missed something.
